[api_keys]
GRID_API_KEY = "e5ikERczUjDeO6ReBanLlyZ4sc07dKNIOtVJcexP"

[connection_strings]
CONNECTION_STRING = "mongodb+srv://admin:1234@datalol.vbw4h.mongodb.net/?retryWrites=true&w=majority&appName=DataLoL"
